version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      # make sure pip/setuptools/wheel is up to date, awscli for SDK patching
      - cd "$CODEBUILD_SRC_DIR_JAVA_PLUGIN"
      - pip install --upgrade pre-commit cloudformation-cli cloudformation-cli-java-plugin  -r "$CODEBUILD_SRC_DIR_RPDK/requirements.txt"
      - mkdir "$CODEBUILD_SRC_DIR_JAVA_PLUGIN/artifacts"
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - pre-commit run --all-files
      - cd namedquery
      - mvn clean verify
    finally:
      - cat "$CODEBUILD_SRC_DIR/namedquery/rpdk.log"
