version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      # make sure pip/setuptools/wheel is up to date, awscli for SDK patching
      - cd "$CODEBUILD_SRC_DIR_JAVA_PLUGIN"
      - pip install --upgrade pip setuptools wheel awscli -r "$CODEBUILD_SRC_DIR_RPDK/requirements.txt"
      - mkdir "$CODEBUILD_SRC_DIR_JAVA_PLUGIN/artifacts"
  build:
    commands:
      # pre-build check for commit hooks
      - pre-commit run --all-files
      # install aws-cloudformation-rpdk
      - pip install cloudformation-cli cloudformation-cli-java-plugin
